export const countries = [
  {
    id: 'kenya',
    name: 'Kenya',
    flag: '🇰🇪',
    currency: 'KES',
    locale: 'en-KE',
    phoneCode: '+254',
    mpesaEnabled: true,
    description: 'Kenya is our home market and the most mature deployment.',
    paymentMethods: ['M-Pesa', 'Cash', 'Card'],
    taxName: 'KRA VAT',
    taxRate: '16%',
    benefits: [
      'Local M-Pesa integration',
      'KRA tax compliance',
      'Local support team',
      'Offline-first for rural areas',
    ],
    comingSoon: false,
  },
  {
    id: 'nigeria',
    name: 'Nigeria',
    flag: '🇳🇬',
    currency: 'NGN',
    locale: 'en-NG',
    phoneCode: '+234',
    mpesaEnabled: false,
    description: 'Expanding across Nigeria with local payment partners.',
    paymentMethods: ['Bank Transfer', 'Cash', 'POS'],
    taxName: 'VAT',
    taxRate: '7.5%',
    benefits: [
      'Local payment integrations',
      'Tax compliance support',
      'English language support',
      'Offline-capable',
    ],
    comingSoon: false,
  },
  {
    id: 'south-africa',
    name: 'South Africa',
    flag: '🇿🇦',
    currency: 'ZAR',
    locale: 'en-ZA',
    phoneCode: '+27',
    mpesaEnabled: false,
    description: 'Available in South Africa with major payment providers.',
    paymentMethods: ['Card', 'Cash', 'EFT'],
    taxName: 'VAT',
    taxRate: '15%',
    benefits: [
      'Local payment integrations',
      'SARS compliance designed',
      'English language support',
      'Offline-first architecture',
    ],
    comingSoon: false,
  },
  {
    id: 'ghana',
    name: 'Ghana',
    flag: '🇬🇭',
    currency: 'GHS',
    locale: 'en-GH',
    phoneCode: '+233',
    mpesaEnabled: false,
    description: 'Coming soon to Ghana.',
    paymentMethods: ['Mobile Money', 'Cash'],
    taxName: 'VAT',
    taxRate: '12.5%',
    benefits: [
      'Planned local integrations',
      'English language support',
      'Offline-first architecture',
    ],
    comingSoon: true,
  },
  {
    id: 'tanzania',
    name: 'Tanzania',
    flag: '🇹🇿',
    currency: 'TZS',
    locale: 'en-TZ',
    phoneCode: '+255',
    mpesaEnabled: true,
    description: 'Coming soon to Tanzania.',
    paymentMethods: ['M-Pesa', 'Cash'],
    taxName: 'VAT',
    taxRate: '18%',
    benefits: [
      'Planned M-Pesa integration',
      'English language support',
      'Offline-first architecture',
    ],
    comingSoon: true,
  },
  {
    id: 'uganda',
    name: 'Uganda',
    flag: '🇺🇬',
    currency: 'UGX',
    locale: 'en-UG',
    phoneCode: '+256',
    mpesaEnabled: false,
    description: 'Coming soon to Uganda.',
    paymentMethods: ['Mobile Money', 'Cash'],
    taxName: 'VAT',
    taxRate: '18%',
    benefits: [
      'Planned local integrations',
      'English language support',
      'Offline-first architecture',
    ],
    comingSoon: true,
  },
  {
    id: 'rwanda',
    name: 'Rwanda',
    flag: '🇷🇼',
    currency: 'RWF',
    locale: 'en-RW',
    phoneCode: '+250',
    mpesaEnabled: false,
    description: 'Coming soon to Rwanda.',
    paymentMethods: ['Mobile Money', 'Cash'],
    taxName: 'VAT',
    taxRate: '18%',
    benefits: [
      'Planned local integrations',
      'English language support',
      'Offline-first architecture',
    ],
    comingSoon: true,
  },
];
