export const products = [
  {
    id: 'pos',
    name: 'Soko POS',
    tagline: 'Point of Sale that works anywhere',
    description: 'Fast, intuitive POS designed for African retail environments. Process sales, manage returns, and track performance even when offline.',
    features: [
      'Offline-first transaction processing',
      'Barcode scanning and product search',
      'Multiple payment methods (Cash, Card, M-Pesa)',
      'Receipt printing (thermal and A4)',
      'Shift management and cashier tracking',
      'Returns and refunds',
    ],
    benefits: [
      'Never lose a sale due to connectivity',
      'Reduce checkout time by 40%',
      'Support for local payment methods',
      'Works on tablets and smartphones',
    ],
    integrations: ['Soko Inventory', 'Soko Pay', 'Soko Books', 'Soko Tax'],
    offlineCapable: true,
    image: '/images/products/pos.svg',
  },
  {
    id: 'inventory',
    name: 'Soko Inventory',
    tagline: 'Stock management that syncs automatically',
    description: 'Track inventory across multiple branches in real-time. Get low-stock alerts, manage purchase orders, and understand your stock movement.',
    features: [
      'Real-time stock tracking',
      'Low stock alerts',
      'Purchase order management',
      'Batch and expiry tracking',
      'Stock transfers between branches',
      'Category and variant management',
    ],
    benefits: [
      'Reduce stockouts by 60%',
      'Automate reordering',
      'Track expiry dates for perishables',
      'Full audit trail',
    ],
    integrations: ['Soko POS', 'Soko Books', 'Soko Analytics'],
    offlineCapable: true,
    image: '/images/products/inventory.svg',
  },
  {
    id: 'commerce',
    name: 'Soko Commerce',
    tagline: 'Accept payments the way your customers prefer',
    description: 'Unified payment processing that supports local mobile money, cards, and bank transfers. Settle funds directly to your business account.',
    features: [
      'M-Pesa integration (Kenya)',
      'Card processing',
      'Bank transfer reconciliation',
      'Split payments',
      'Refund management',
      'Settlement reports',
    ],
    benefits: [
      'Accept any payment method',
      'Get paid faster with direct settlement',
      'Reconcile payments automatically',
      'Lower transaction fees',
    ],
    integrations: ['Soko POS', 'Soko Books', 'Soko Tax'],
    offlineCapable: false,
    image: '/images/products/pay.svg',
  },
  {
    id: 'books',
    name: 'Soko Books',
    tagline: 'Accounting that actually makes sense',
    description: 'Full double-entry bookkeeping designed for African businesses. Track income, expenses, and generate financial statements.',
    features: [
      'Double-entry bookkeeping',
      'Chart of accounts',
      'Bank reconciliation',
      'Invoice management',
      'Expense tracking',
      'Financial statements (P&L, Balance Sheet)',
    ],
    benefits: [
      'Know your true profitability',
      'Make data-driven decisions',
      'Simplify tax season',
      'Works offline',
    ],
    integrations: ['Soko POS', 'Soko Inventory', 'Soko Tax', 'Soko Pay'],
    offlineCapable: true,
    image: '/images/products/books.svg',
  },
  {
    id: 'insights',
    name: 'Soko Insights',
    tagline: 'Turn your data into decisions',
    description: 'Powerful analytics dashboard with sales trends, inventory insights, and business health metrics. Make decisions with confidence.',
    features: [
      'Real-time sales dashboard',
      'Top products and categories',
      'Sales by hour and day',
      'Inventory turnover reports',
      'Customer insights',
      'Branch comparison',
    ],
    benefits: [
      'Spot trends before competitors',
      'Optimize stock levels',
      'Identify top-performing items',
      'Branch performance benchmarking',
    ],
    integrations: ['Soko POS', 'Soko Inventory', 'Soko Books'],
    offlineCapable: false,
    image: '/images/products/analytics.svg',
  },
  {
    id: 'procurement',
    name: 'Soko Procurement',
    tagline: 'Integrate everything into one system',
    description: 'Open APIs and webhooks to connect Soko-OS with your existing tools. Build custom integrations or use our pre-built connectors.',
    features: [
      'REST API access',
      'Webhooks for real-time events',
      'Pre-built connectors',
      'Custom integration support',
      'Data export (CSV, Excel, PDF)',
      'Developer documentation',
    ],
    benefits: [
      'Connect to any system',
      'Automate workflows',
      'Keep existing tools',
      'Scale without limits',
    ],
    integrations: ['All Soko-OS products', 'Third-party ERP', 'Custom systems'],
    offlineCapable: true,
    image: '/images/products/connect.svg',
  },
  {
    id: 'crm',
    name: 'Soko CRM',
    tagline: 'Customer relationships that grow your business',
    description: 'Manage leads, contacts, deals, and customer relationships. Track your sales pipeline and close more deals.',
    features: [
      'Lead and contact management',
      'Deal pipeline tracking',
      'Activity and task management',
      'Email and communication tracking',
      'Sales forecasting',
      'Customer segmentation',
    ],
    benefits: [
      'Never miss a follow-up',
      'Close deals faster',
      'Understand your customers',
      'Forecast revenue accurately',
    ],
    integrations: ['Soko POS', 'Soko Commerce', 'Soko Books'],
    offlineCapable: true,
    image: '/images/products/connect.svg',
  },
];

export const productById = (id: string) => products.find((p) => p.id === id);