export const solutions = [
  {
    id: 'retail',
    name: 'Retail Shops',
    icon: 'Store',
    description: 'For small to medium retail shops looking to digitize operations.',
    painPoints: [
      'Manual stock tracking leads to losses',
      'No visibility into sales trends',
      'Cash handling is risky',
      'No way to track customer purchases',
    ],
    features: [
      'Quick product lookup and checkout',
      'Inventory tracking with low-stock alerts',
      'Multiple payment methods',
      'Daily sales summaries',
      'Customer purchase history',
    ],
    cta: 'Explore Retail Solution',
  },
  {
    id: 'supermarkets',
    name: 'Supermarkets',
    icon: 'ShoppingCart',
    description: 'For supermarkets managing high volumes across multiple departments.',
    painPoints: [
      'Long queues during peak hours',
      'Inventory management across departments',
      'Price updates across many items',
      'Multi-cashier coordination',
    ],
    features: [
      'Multiple simultaneous registers',
      'Department management',
      'Bulk price updates',
      'Promotions and discounts',
      'Queue management',
      'Shift tracking',
    ],
    cta: 'Explore Supermarket Solution',
  },
  {
    id: 'restaurants',
    name: 'Restaurants',
    icon: 'Utensils',
    description: 'For restaurants, cafes, and quick service outlets.',
    painPoints: [
      'Order taking is slow',
      'Kitchen communication breaks down',
      'Table management is chaotic',
      'Split bills are difficult',
    ],
    features: [
      'Table management and floor plans',
      'Course timing for kitchen',
      'Split bills and combined payments',
      'Modifiers and variants (size, toppings)',
      'Kitchen display integration',
      'Service charge automation',
    ],
    cta: 'Explore Restaurant Solution',
  },
  {
    id: 'pharmacies',
    name: 'Pharmacies',
    icon: 'HeartPulse',
    description: 'For pharmacies that need to manage prescriptions and regulated products.',
    painPoints: [
      'Tracking prescription records',
      'Managing drug expiry dates',
      'Compliance with pharmacy regulations',
      'Inventory of controlled substances',
    ],
    features: [
      'Prescription tracking',
      'Expiry date alerts',
      'Batch tracking for recalls',
      'Regulated product management',
      'Customer medication history',
      'Compliance reporting',
    ],
    cta: 'Explore Pharmacy Solution',
  },
  {
    id: 'wholesale',
    name: 'Wholesale & Distributors',
    icon: 'Truck',
    description: 'For wholesalers and distributors managing bulk orders and credit.',
    painPoints: [
      'Credit management is complex',
      'Bulk pricing tiers',
      'Delivery scheduling',
      'Large catalog management',
    ],
    features: [
      'Credit limits and aging',
      'Tiered pricing per customer',
      'Bulk order processing',
      'Delivery route management',
      'Customer statement generation',
      'Sales representative tracking',
    ],
    cta: 'Explore Wholesale Solution',
  },
  {
    id: 'distribution',
    name: 'Distribution',
    icon: 'Package',
    description: 'For distributors moving goods between warehouses and retail outlets.',
    painPoints: [
      'Tracking goods in transit',
      'Multi-warehouse coordination',
      'Route optimization',
      'Proof of delivery',
    ],
    features: [
      'Goods in transit tracking',
      'Multi-warehouse management',
      'Route planning',
      'Proof of delivery capture',
      'Fleet management integration',
      'Returns processing',
    ],
    cta: 'Explore Distribution Solution',
  },
  {
    id: 'multi-branch',
    name: 'Multi-Branch',
    icon: 'Building2',
    description: 'For businesses operating multiple locations.',
    painPoints: [
      'No visibility across branches',
      'Inconsistent pricing',
      'Centralized reporting is manual',
      'Stock transfers are error-prone',
    ],
    features: [
      'Centralized dashboard',
      'Branch-specific pricing',
      'Inter-branch stock transfers',
      'Consolidated financial reports',
      'Role-based access per branch',
      'Branch performance comparison',
    ],
    cta: 'Explore Multi-Branch Solution',
  },
];
