import { Product, Sale, Customer, CashShift, Category, Organization, Business, Branch, Warehouse, Terminal, Device, Supplier, PurchaseOrder, GoodsReceivedNote, Refund, ReturnModel, Account, JournalEntry, ReportData, Invoice, Bill, Quote, SalesOrder, CreditNote, DebitNote, Expense, BankAccount, BankTransaction, BankReconciliation, FiscalYear, AccountingPeriod, TaxRate, Lead, CrmAccount, Contact, Deal, Pipeline, Campaign, CaseModel, PurchaseRequisition, Rfq, Tender, SupplierInvoice, ThreeWayMatch, PaymentVoucher, SupplierPayment, PaymentReconciliation, ProcurementContract, ApprovalRule } from '@soko/domain-types';

export const queryKeys = {
  products: {
    all: ['products'] as const,
    lists: () => [...queryKeys.products.all, 'list'] as const,
    list: (filters?: Record<string, unknown>) => [...queryKeys.products.lists(), filters] as const,
    details: () => [...queryKeys.products.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.products.details(), id] as const,
  },
  categories: {
    all: ['categories'] as const,
    lists: () => [...queryKeys.categories.all, 'list'] as const,
    list: () => [...queryKeys.categories.lists()] as const,
    details: () => [...queryKeys.categories.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.categories.details(), id] as const,
  },
  customers: {
    all: ['customers'] as const,
    lists: () => [...queryKeys.customers.all, 'list'] as const,
    list: (filters?: Record<string, unknown>) => [...queryKeys.customers.lists(), filters] as const,
    details: () => [...queryKeys.customers.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.customers.details(), id] as const,
  },
  sales: {
    all: ['sales'] as const,
    lists: () => [...queryKeys.sales.all, 'list'] as const,
    list: (filters?: Record<string, unknown>) => [...queryKeys.sales.lists(), filters] as const,
    details: () => [...queryKeys.sales.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.sales.details(), id] as const,
  },
  shifts: {
    all: ['shifts'] as const,
    current: ['shifts', 'current'] as const,
  },
  organizations: {
    all: ['organizations'] as const,
    lists: () => [...queryKeys.organizations.all, 'list'] as const,
    list: () => [...queryKeys.organizations.lists()] as const,
    details: () => [...queryKeys.organizations.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.organizations.details(), id] as const,
  },
  businesses: {
    all: ['businesses'] as const,
    lists: () => [...queryKeys.businesses.all, 'list'] as const,
    list: (orgId: string) => [...queryKeys.businesses.lists(), orgId] as const,
    details: () => [...queryKeys.businesses.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.businesses.details(), id] as const,
  },
  branches: {
    all: ['branches'] as const,
    lists: () => [...queryKeys.branches.all, 'list'] as const,
    list: (orgId?: string) => [...queryKeys.branches.lists(), orgId] as const,
    details: () => [...queryKeys.branches.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.branches.details(), id] as const,
  },
  warehouses: {
    all: ['warehouses'] as const,
    lists: () => [...queryKeys.warehouses.all, 'list'] as const,
    list: (orgId?: string) => [...queryKeys.warehouses.lists(), orgId] as const,
    details: () => [...queryKeys.warehouses.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.warehouses.details(), id] as const,
  },
  terminals: {
    all: ['terminals'] as const,
    lists: () => [...queryKeys.terminals.all, 'list'] as const,
    list: (orgId?: string) => [...queryKeys.terminals.lists(), orgId] as const,
    details: () => [...queryKeys.terminals.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.terminals.details(), id] as const,
  },
  devices: {
    all: ['devices'] as const,
    lists: () => [...queryKeys.devices.all, 'list'] as const,
    list: (orgId?: string) => [...queryKeys.devices.lists(), orgId] as const,
    details: () => [...queryKeys.devices.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.devices.details(), id] as const,
  },
  suppliers: {
    all: ['suppliers'] as const,
    lists: () => [...queryKeys.suppliers.all, 'list'] as const,
    list: () => [...queryKeys.suppliers.lists()] as const,
    details: () => [...queryKeys.suppliers.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.suppliers.details(), id] as const,
  },
  purchaseOrders: {
    all: ['purchase-orders'] as const,
    lists: () => [...queryKeys.purchaseOrders.all, 'list'] as const,
    list: () => [...queryKeys.purchaseOrders.lists()] as const,
    details: () => [...queryKeys.purchaseOrders.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.purchaseOrders.details(), id] as const,
  },
  grns: {
    all: ['grns'] as const,
    lists: () => [...queryKeys.grns.all, 'list'] as const,
    list: () => [...queryKeys.grns.lists()] as const,
    details: () => [...queryKeys.grns.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.grns.details(), id] as const,
  },
  refunds: {
    all: ['refunds'] as const,
    lists: () => [...queryKeys.refunds.all, 'list'] as const,
    list: (filters?: Record<string, unknown>) => [...queryKeys.refunds.lists(), filters] as const,
    details: () => [...queryKeys.refunds.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.refunds.details(), id] as const,
  },
  returns: {
    all: ['returns'] as const,
    lists: () => [...queryKeys.returns.all, 'list'] as const,
    list: (filters?: Record<string, unknown>) => [...queryKeys.returns.lists(), filters] as const,
    details: () => [...queryKeys.returns.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.returns.details(), id] as const,
  },
  payments: {
    all: ['payments'] as const,
    lists: () => [...queryKeys.payments.all, 'list'] as const,
    list: (filters?: Record<string, unknown>) => [...queryKeys.payments.lists(), filters] as const,
    details: () => [...queryKeys.payments.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.payments.details(), id] as const,
  },
  accounts: {
    all: ['accounts'] as const,
    lists: () => [...queryKeys.accounts.all, 'list'] as const,
    list: (filters?: Record<string, unknown>) => [...queryKeys.accounts.lists(), filters] as const,
    details: () => [...queryKeys.accounts.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.accounts.details(), id] as const,
  },
  journalEntries: {
    all: ['journal-entries'] as const,
    lists: () => [...queryKeys.journalEntries.all, 'list'] as const,
    list: (filters?: Record<string, unknown>) => [...queryKeys.journalEntries.lists(), filters] as const,
    details: () => [...queryKeys.journalEntries.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.journalEntries.details(), id] as const,
  },
  roles: {
    all: ['roles'] as const,
    lists: () => [...queryKeys.roles.all, 'list'] as const,
    list: () => [...queryKeys.roles.lists()] as const,
    details: () => [...queryKeys.roles.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.roles.details(), id] as const,
  },
  permissions: {
    all: ['permissions'] as const,
    lists: () => [...queryKeys.permissions.all, 'list'] as const,
    list: () => [...queryKeys.permissions.lists()] as const,
  },
  reports: {
    all: ['reports'] as const,
    sales: ['reports', 'sales'] as const,
    inventory: ['reports', 'inventory'] as const,
    tax: ['reports', 'tax'] as const,
    ledger: ['reports', 'ledger'] as const,
    trialBalance: ['reports', 'trial-balance'] as const,
    profitLoss: ['reports', 'profit-loss'] as const,
    balanceSheet: ['reports', 'balance-sheet'] as const,
  },
  invoices: {
    all: ['invoices'] as const,
    lists: () => [...queryKeys.invoices.all, 'list'] as const,
    list: (filters?: Record<string, unknown>) => [...queryKeys.invoices.lists(), filters] as const,
    details: () => [...queryKeys.invoices.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.invoices.details(), id] as const,
  },
  bills: {
    all: ['bills'] as const,
    lists: () => [...queryKeys.bills.all, 'list'] as const,
    list: (filters?: Record<string, unknown>) => [...queryKeys.bills.lists(), filters] as const,
    details: () => [...queryKeys.bills.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.bills.details(), id] as const,
  },
  expenses: {
    all: ['expenses'] as const,
    lists: () => [...queryKeys.expenses.all, 'list'] as const,
    list: (filters?: Record<string, unknown>) => [...queryKeys.expenses.lists(), filters] as const,
    details: () => [...queryKeys.expenses.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.expenses.details(), id] as const,
  },
  bankAccounts: {
    all: ['bank-accounts'] as const,
    lists: () => [...queryKeys.bankAccounts.all, 'list'] as const,
    list: (filters?: Record<string, unknown>) => [...queryKeys.bankAccounts.lists(), filters] as const,
    details: () => [...queryKeys.bankAccounts.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.bankAccounts.details(), id] as const,
  },
  bankTransactions: {
    all: ['bank-transactions'] as const,
    lists: () => [...queryKeys.bankTransactions.all, 'list'] as const,
    list: (filters?: Record<string, unknown>) => [...queryKeys.bankTransactions.lists(), filters] as const,
    details: () => [...queryKeys.bankTransactions.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.bankTransactions.details(), id] as const,
  },
  fiscalYears: {
    all: ['fiscal-years'] as const,
    lists: () => [...queryKeys.fiscalYears.all, 'list'] as const,
    list: (filters?: Record<string, unknown>) => [...queryKeys.fiscalYears.lists(), filters] as const,
    details: () => [...queryKeys.fiscalYears.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.fiscalYears.details(), id] as const,
  },
  accountingPeriods: {
    all: ['accounting-periods'] as const,
    lists: () => [...queryKeys.accountingPeriods.all, 'list'] as const,
    list: (filters?: Record<string, unknown>) => [...queryKeys.accountingPeriods.lists(), filters] as const,
    details: () => [...queryKeys.accountingPeriods.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.accountingPeriods.details(), id] as const,
  },
  taxRates: {
    all: ['tax-rates'] as const,
    lists: () => [...queryKeys.taxRates.all, 'list'] as const,
    list: (filters?: Record<string, unknown>) => [...queryKeys.taxRates.lists(), filters] as const,
    details: () => [...queryKeys.taxRates.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.taxRates.details(), id] as const,
  },
  leads: {
    all: ['crm', 'leads'] as const,
    lists: () => [...queryKeys.leads.all, 'list'] as const,
    list: (filters?: Record<string, unknown>) => [...queryKeys.leads.lists(), filters] as const,
    details: () => [...queryKeys.leads.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.leads.details(), id] as const,
  },
  crmAccounts: {
    all: ['crm', 'accounts'] as const,
    lists: () => [...queryKeys.crmAccounts.all, 'list'] as const,
    list: (filters?: Record<string, unknown>) => [...queryKeys.crmAccounts.lists(), filters] as const,
    details: () => [...queryKeys.crmAccounts.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.crmAccounts.details(), id] as const,
  },
  contacts: {
    all: ['crm', 'contacts'] as const,
    lists: () => [...queryKeys.contacts.all, 'list'] as const,
    list: (filters?: Record<string, unknown>) => [...queryKeys.contacts.lists(), filters] as const,
    details: () => [...queryKeys.contacts.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.contacts.details(), id] as const,
  },
  deals: {
    all: ['crm', 'deals'] as const,
    lists: () => [...queryKeys.deals.all, 'list'] as const,
    list: (filters?: Record<string, unknown>) => [...queryKeys.deals.lists(), filters] as const,
    details: () => [...queryKeys.deals.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.deals.details(), id] as const,
  },
  pipelines: {
    all: ['crm', 'pipelines'] as const,
    lists: () => [...queryKeys.pipelines.all, 'list'] as const,
    list: (filters?: Record<string, unknown>) => [...queryKeys.pipelines.lists(), filters] as const,
    details: () => [...queryKeys.pipelines.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.pipelines.details(), id] as const,
  },
  campaigns: {
    all: ['crm', 'campaigns'] as const,
    lists: () => [...queryKeys.campaigns.all, 'list'] as const,
    list: (filters?: Record<string, unknown>) => [...queryKeys.campaigns.lists(), filters] as const,
    details: () => [...queryKeys.campaigns.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.campaigns.details(), id] as const,
  },
  cases: {
    all: ['crm', 'cases'] as const,
    lists: () => [...queryKeys.cases.all, 'list'] as const,
    list: (filters?: Record<string, unknown>) => [...queryKeys.cases.lists(), filters] as const,
    details: () => [...queryKeys.cases.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.cases.details(), id] as const,
  },
  dealStages: {
    all: ['crm', 'deal-stages'] as const,
    lists: () => [...queryKeys.dealStages.all, 'list'] as const,
    list: (filters?: Record<string, unknown>) => [...queryKeys.dealStages.lists(), filters] as const,
    details: () => [...queryKeys.dealStages.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.dealStages.details(), id] as const,
  },
  activities: {
    all: ['crm', 'activities'] as const,
    lists: () => [...queryKeys.activities.all, 'list'] as const,
    list: (filters?: Record<string, unknown>) => [...queryKeys.activities.lists(), filters] as const,
    details: () => [...queryKeys.activities.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.activities.details(), id] as const,
  },
  communications: {
    all: ['crm', 'communications'] as const,
    lists: () => [...queryKeys.communications.all, 'list'] as const,
    list: (filters?: Record<string, unknown>) => [...queryKeys.communications.lists(), filters] as const,
    details: () => [...queryKeys.communications.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.communications.details(), id] as const,
  },
  workflows: {
    all: ['crm', 'workflows'] as const,
    lists: () => [...queryKeys.workflows.all, 'list'] as const,
    list: (filters?: Record<string, unknown>) => [...queryKeys.workflows.lists(), filters] as const,
    details: () => [...queryKeys.workflows.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.workflows.details(), id] as const,
  },
  slas: {
    all: ['crm', 'slas'] as const,
    lists: () => [...queryKeys.slas.all, 'list'] as const,
    list: (filters?: Record<string, unknown>) => [...queryKeys.slas.lists(), filters] as const,
    details: () => [...queryKeys.slas.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.slas.details(), id] as const,
  },
  customFields: {
    all: ['crm', 'custom-fields'] as const,
    lists: () => [...queryKeys.customFields.all, 'list'] as const,
    list: (filters?: Record<string, unknown>) => [...queryKeys.customFields.lists(), filters] as const,
    details: () => [...queryKeys.customFields.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.customFields.details(), id] as const,
  },
  territories: {
    all: ['crm', 'territories'] as const,
    lists: () => [...queryKeys.territories.all, 'list'] as const,
    list: (filters?: Record<string, unknown>) => [...queryKeys.territories.lists(), filters] as const,
    details: () => [...queryKeys.territories.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.territories.details(), id] as const,
  },
  priceBooks: {
    all: ['crm', 'price-books'] as const,
    lists: () => [...queryKeys.priceBooks.all, 'list'] as const,
    list: (filters?: Record<string, unknown>) => [...queryKeys.priceBooks.lists(), filters] as const,
    details: () => [...queryKeys.priceBooks.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.priceBooks.details(), id] as const,
  },
  knowledgeArticles: {
    all: ['crm', 'knowledge'] as const,
    lists: () => [...queryKeys.knowledgeArticles.all, 'list'] as const,
    list: (filters?: Record<string, unknown>) => [...queryKeys.knowledgeArticles.lists(), filters] as const,
    details: () => [...queryKeys.knowledgeArticles.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.knowledgeArticles.details(), id] as const,
  },
  sequences: {
    all: ['crm', 'sequences'] as const,
    lists: () => [...queryKeys.sequences.all, 'list'] as const,
    list: (filters?: Record<string, unknown>) => [...queryKeys.sequences.lists(), filters] as const,
    details: () => [...queryKeys.sequences.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.sequences.details(), id] as const,
  },
  leadScoringRules: {
    all: ['crm', 'lead-scoring-rules'] as const,
    lists: () => [...queryKeys.leadScoringRules.all, 'list'] as const,
    list: (filters?: Record<string, unknown>) => [...queryKeys.leadScoringRules.lists(), filters] as const,
    details: () => [...queryKeys.leadScoringRules.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.leadScoringRules.details(), id] as const,
  },
  leadAssignments: {
    all: ['crm', 'lead-assignments'] as const,
    lists: () => [...queryKeys.leadAssignments.all, 'list'] as const,
    list: (filters?: Record<string, unknown>) => [...queryKeys.leadAssignments.lists(), filters] as const,
    details: () => [...queryKeys.leadAssignments.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.leadAssignments.details(), id] as const,
  },
  procurement: {
    requisitions: {
      all: ['procurement', 'requisitions'] as const,
      lists: () => [...queryKeys.procurement.requisitions.all, 'list'] as const,
      list: (filters?: Record<string, unknown>) => [...queryKeys.procurement.requisitions.lists(), filters] as const,
      details: () => [...queryKeys.procurement.requisitions.all, 'detail'] as const,
      detail: (id: string) => [...queryKeys.procurement.requisitions.details(), id] as const,
    },
    rfqs: {
      all: ['procurement', 'rfqs'] as const,
      lists: () => [...queryKeys.procurement.rfqs.all, 'list'] as const,
      list: (filters?: Record<string, unknown>) => [...queryKeys.procurement.rfqs.lists(), filters] as const,
      details: () => [...queryKeys.procurement.rfqs.all, 'detail'] as const,
      detail: (id: string) => [...queryKeys.procurement.rfqs.details(), id] as const,
    },
    tenders: {
      all: ['procurement', 'tenders'] as const,
      lists: () => [...queryKeys.procurement.tenders.all, 'list'] as const,
      list: (filters?: Record<string, unknown>) => [...queryKeys.procurement.tenders.lists(), filters] as const,
      details: () => [...queryKeys.procurement.tenders.all, 'detail'] as const,
      detail: (id: string) => [...queryKeys.procurement.tenders.details(), id] as const,
    },
    invoices: {
      all: ['procurement', 'invoices'] as const,
      lists: () => [...queryKeys.procurement.invoices.all, 'list'] as const,
      list: (filters?: Record<string, unknown>) => [...queryKeys.procurement.invoices.lists(), filters] as const,
      details: () => [...queryKeys.procurement.invoices.all, 'detail'] as const,
      detail: (id: string) => [...queryKeys.procurement.invoices.details(), id] as const,
    },
    matches: {
      all: ['procurement', 'matches'] as const,
      lists: () => [...queryKeys.procurement.matches.all, 'list'] as const,
      list: (filters?: Record<string, unknown>) => [...queryKeys.procurement.matches.lists(), filters] as const,
      details: () => [...queryKeys.procurement.matches.all, 'detail'] as const,
      detail: (id: string) => [...queryKeys.procurement.matches.details(), id] as const,
    },
    paymentVouchers: {
      all: ['procurement', 'payment-vouchers'] as const,
      lists: () => [...queryKeys.procurement.paymentVouchers.all, 'list'] as const,
      list: (filters?: Record<string, unknown>) => [...queryKeys.procurement.paymentVouchers.lists(), filters] as const,
      details: () => [...queryKeys.procurement.paymentVouchers.all, 'detail'] as const,
      detail: (id: string) => [...queryKeys.procurement.paymentVouchers.details(), id] as const,
    },
    payments: {
      all: ['procurement', 'payments'] as const,
      lists: () => [...queryKeys.procurement.payments.all, 'list'] as const,
      list: (filters?: Record<string, unknown>) => [...queryKeys.procurement.payments.lists(), filters] as const,
      details: () => [...queryKeys.procurement.payments.all, 'detail'] as const,
      detail: (id: string) => [...queryKeys.procurement.payments.details(), id] as const,
    },
    reconciliations: {
      all: ['procurement', 'reconciliations'] as const,
      lists: () => [...queryKeys.procurement.reconciliations.all, 'list'] as const,
      list: (filters?: Record<string, unknown>) => [...queryKeys.procurement.reconciliations.lists(), filters] as const,
      details: () => [...queryKeys.procurement.reconciliations.all, 'detail'] as const,
      detail: (id: string) => [...queryKeys.procurement.reconciliations.details(), id] as const,
    },
    contracts: {
      all: ['procurement', 'contracts'] as const,
      lists: () => [...queryKeys.procurement.contracts.all, 'list'] as const,
      list: (filters?: Record<string, unknown>) => [...queryKeys.procurement.contracts.lists(), filters] as const,
      details: () => [...queryKeys.procurement.contracts.all, 'detail'] as const,
      detail: (id: string) => [...queryKeys.procurement.contracts.details(), id] as const,
    },
    approvalRules: {
      all: ['procurement', 'approval-rules'] as const,
      lists: () => [...queryKeys.procurement.approvalRules.all, 'list'] as const,
      list: (filters?: Record<string, unknown>) => [...queryKeys.procurement.approvalRules.lists(), filters] as const,
      details: () => [...queryKeys.procurement.approvalRules.all, 'detail'] as const,
      detail: (id: string) => [...queryKeys.procurement.approvalRules.details(), id] as const,
    },
  },
  auth: {
    me: ['auth', 'me'] as const,
    entitlements: ['auth', 'entitlements'] as const,
  },
};
