import { Product, Sale, Customer, CashShift, Category, Organization, Business, Branch, Warehouse, Terminal, Device, Supplier, PurchaseOrder, GoodsReceivedNote, Refund, ReturnModel, Account, JournalEntry, ReportData } from '@soko/domain-types';

export const queryKeys = {
  products: {
    all: ['products'] as const,
    lists: () => [...queryKeys.products.all, 'list'] as const,
    list: (filters?: Record<string, unknown>) => [...queryKeys.products.lists(), filters] as const,
    details: () => [...queryKeys.products.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.products.details(), id] as const,
  },
  categories: {
    all: ['categories'] as const,
    lists: () => [...queryKeys.categories.all, 'list'] as const,
    list: () => [...queryKeys.categories.lists()] as const,
    details: () => [...queryKeys.categories.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.categories.details(), id] as const,
  },
  customers: {
    all: ['customers'] as const,
    lists: () => [...queryKeys.customers.all, 'list'] as const,
    list: (filters?: Record<string, unknown>) => [...queryKeys.customers.lists(), filters] as const,
    details: () => [...queryKeys.customers.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.customers.details(), id] as const,
  },
  sales: {
    all: ['sales'] as const,
    lists: () => [...queryKeys.sales.all, 'list'] as const,
    list: (filters?: Record<string, unknown>) => [...queryKeys.sales.lists(), filters] as const,
    details: () => [...queryKeys.sales.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.sales.details(), id] as const,
  },
  shifts: {
    all: ['shifts'] as const,
    current: ['shifts', 'current'] as const,
  },
  organizations: {
    all: ['organizations'] as const,
    lists: () => [...queryKeys.organizations.all, 'list'] as const,
    list: () => [...queryKeys.organizations.lists()] as const,
    details: () => [...queryKeys.organizations.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.organizations.details(), id] as const,
  },
  businesses: {
    all: ['businesses'] as const,
    lists: () => [...queryKeys.businesses.all, 'list'] as const,
    list: (orgId: string) => [...queryKeys.businesses.lists(), orgId] as const,
    details: () => [...queryKeys.businesses.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.businesses.details(), id] as const,
  },
  branches: {
    all: ['branches'] as const,
    lists: () => [...queryKeys.branches.all, 'list'] as const,
    list: (orgId?: string) => [...queryKeys.branches.lists(), orgId] as const,
    details: () => [...queryKeys.branches.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.branches.details(), id] as const,
  },
  warehouses: {
    all: ['warehouses'] as const,
    lists: () => [...queryKeys.warehouses.all, 'list'] as const,
    list: (orgId?: string) => [...queryKeys.warehouses.lists(), orgId] as const,
    details: () => [...queryKeys.warehouses.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.warehouses.details(), id] as const,
  },
  terminals: {
    all: ['terminals'] as const,
    lists: () => [...queryKeys.terminals.all, 'list'] as const,
    list: (orgId?: string) => [...queryKeys.terminals.lists(), orgId] as const,
    details: () => [...queryKeys.terminals.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.terminals.details(), id] as const,
  },
  devices: {
    all: ['devices'] as const,
    lists: () => [...queryKeys.devices.all, 'list'] as const,
    list: (orgId?: string) => [...queryKeys.devices.lists(), orgId] as const,
    details: () => [...queryKeys.devices.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.devices.details(), id] as const,
  },
  suppliers: {
    all: ['suppliers'] as const,
    lists: () => [...queryKeys.suppliers.all, 'list'] as const,
    list: () => [...queryKeys.suppliers.lists()] as const,
    details: () => [...queryKeys.suppliers.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.suppliers.details(), id] as const,
  },
  purchaseOrders: {
    all: ['purchase-orders'] as const,
    lists: () => [...queryKeys.purchaseOrders.all, 'list'] as const,
    list: () => [...queryKeys.purchaseOrders.lists()] as const,
    details: () => [...queryKeys.purchaseOrders.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.purchaseOrders.details(), id] as const,
  },
  grns: {
    all: ['grns'] as const,
    lists: () => [...queryKeys.grns.all, 'list'] as const,
    list: () => [...queryKeys.grns.lists()] as const,
    details: () => [...queryKeys.grns.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.grns.details(), id] as const,
  },
  refunds: {
    all: ['refunds'] as const,
    lists: () => [...queryKeys.refunds.all, 'list'] as const,
    list: (filters?: Record<string, unknown>) => [...queryKeys.refunds.lists(), filters] as const,
    details: () => [...queryKeys.refunds.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.refunds.details(), id] as const,
  },
  returns: {
    all: ['returns'] as const,
    lists: () => [...queryKeys.returns.all, 'list'] as const,
    list: (filters?: Record<string, unknown>) => [...queryKeys.returns.lists(), filters] as const,
    details: () => [...queryKeys.returns.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.returns.details(), id] as const,
  },
  payments: {
    all: ['payments'] as const,
    lists: () => [...queryKeys.payments.all, 'list'] as const,
    list: (filters?: Record<string, unknown>) => [...queryKeys.payments.lists(), filters] as const,
    details: () => [...queryKeys.payments.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.payments.details(), id] as const,
  },
  accounts: {
    all: ['accounts'] as const,
    lists: () => [...queryKeys.accounts.all, 'list'] as const,
    list: (filters?: Record<string, unknown>) => [...queryKeys.accounts.lists(), filters] as const,
    details: () => [...queryKeys.accounts.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.accounts.details(), id] as const,
  },
  journalEntries: {
    all: ['journal-entries'] as const,
    lists: () => [...queryKeys.journalEntries.all, 'list'] as const,
    list: (filters?: Record<string, unknown>) => [...queryKeys.journalEntries.lists(), filters] as const,
    details: () => [...queryKeys.journalEntries.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.journalEntries.details(), id] as const,
  },
  roles: {
    all: ['roles'] as const,
    lists: () => [...queryKeys.roles.all, 'list'] as const,
    list: () => [...queryKeys.roles.lists()] as const,
    details: () => [...queryKeys.roles.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.roles.details(), id] as const,
  },
  permissions: {
    all: ['permissions'] as const,
    lists: () => [...queryKeys.permissions.all, 'list'] as const,
    list: () => [...queryKeys.permissions.lists()] as const,
  },
  reports: {
    all: ['reports'] as const,
    sales: ['reports', 'sales'] as const,
    inventory: ['reports', 'inventory'] as const,
    tax: ['reports', 'tax'] as const,
    ledger: ['reports', 'ledger'] as const,
    trialBalance: ['reports', 'trial-balance'] as const,
    profitLoss: ['reports', 'profit-loss'] as const,
    balanceSheet: ['reports', 'balance-sheet'] as const,
  },
  invoices: {
    all: ['invoices'] as const,
    lists: () => [...queryKeys.invoices.all, 'list'] as const,
    list: (filters?: Record<string, unknown>) => [...queryKeys.invoices.lists(), filters] as const,
    details: () => [...queryKeys.invoices.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.invoices.details(), id] as const,
  },
  bills: {
    all: ['bills'] as const,
    lists: () => [...queryKeys.bills.all, 'list'] as const,
    list: (filters?: Record<string, unknown>) => [...queryKeys.bills.lists(), filters] as const,
    details: () => [...queryKeys.bills.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.bills.details(), id] as const,
  },
  expenses: {
    all: ['expenses'] as const,
    lists: () => [...queryKeys.expenses.all, 'list'] as const,
    list: (filters?: Record<string, unknown>) => [...queryKeys.expenses.lists(), filters] as const,
    details: () => [...queryKeys.expenses.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.expenses.details(), id] as const,
  },
  bankAccounts: {
    all: ['bank-accounts'] as const,
    lists: () => [...queryKeys.bankAccounts.all, 'list'] as const,
    list: (filters?: Record<string, unknown>) => [...queryKeys.bankAccounts.lists(), filters] as const,
    details: () => [...queryKeys.bankAccounts.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.bankAccounts.details(), id] as const,
  },
  bankTransactions: {
    all: ['bank-transactions'] as const,
    lists: () => [...queryKeys.bankTransactions.all, 'list'] as const,
    list: (filters?: Record<string, unknown>) => [...queryKeys.bankTransactions.lists(), filters] as const,
    details: () => [...queryKeys.bankTransactions.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.bankTransactions.details(), id] as const,
  },
  fiscalYears: {
    all: ['fiscal-years'] as const,
    lists: () => [...queryKeys.fiscalYears.all, 'list'] as const,
    list: (filters?: Record<string, unknown>) => [...queryKeys.fiscalYears.lists(), filters] as const,
    details: () => [...queryKeys.fiscalYears.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.fiscalYears.details(), id] as const,
  },
  accountingPeriods: {
    all: ['accounting-periods'] as const,
    lists: () => [...queryKeys.accountingPeriods.all, 'list'] as const,
    list: (filters?: Record<string, unknown>) => [...queryKeys.accountingPeriods.lists(), filters] as const,
    details: () => [...queryKeys.accountingPeriods.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.accountingPeriods.details(), id] as const,
  },
  taxRates: {
    all: ['tax-rates'] as const,
    lists: () => [...queryKeys.taxRates.all, 'list'] as const,
    list: (filters?: Record<string, unknown>) => [...queryKeys.taxRates.lists(), filters] as const,
    details: () => [...queryKeys.taxRates.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.taxRates.details(), id] as const,
  },
  auth: {
    me: ['auth', 'me'] as const,
    entitlements: ['auth', 'entitlements'] as const,
  },
};
